#!/bin/sh
cat $1 | sed -e '1,87d' | \
         sed -e 's/h4/h6/g' | \
         sed -e 's/h3/h5/g' | \
         sed -e 's/h2/h4/g' | \
         sed -e 's/\/images/http:\/\/gosyujin.github.com\/images/g'
